name: abbi
description: "Mod Manager for OMORI"

publish_to: "none"

version: 0.143.4-beta

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  archive: ^4.0.2
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.3
  flutter_settings_screens: ^0.3.4
  hooks_riverpod: ^3.0.0-dev.3
  intl: any
  package_info_plus: ^8.0.2
  path: ^1.9.0
  random_string: ^2.3.1
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  vdf: ^1.1.0
  win32_registry: ^2.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  meta: ^1.16.0

flutter:
  uses-material-design: true
  assets:
    - .git/HEAD
    - .git/refs/heads/
  generate: true
