name: abbi
description: "Mod Manager for OMORI"

publish_to: "none"

version: 0.2.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  archive: ^3.6.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^3.0.0-dev.3
  hooks_riverpod: ^3.0.0-dev.3
  package_info_plus: ^8.0.2
  path: ^1.9.0
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.0
  win32_registry: ^1.1.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .git/HEAD
    - .git/refs/heads/
