name: Flutter Windows Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build Windows release
      run: flutter build windows --release

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: build/windows/x64/runner/Release/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/windows/x64/runner/Release/*
        prerelease: ${{ contains(github.ref, '-beta') || contains(github.ref, '-alpha') }}