name: Flutter Windows Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build Windows release
      run: flutter build windows --release

    - name: Create Zip Archive
      run: |
        $sourcePath = "build/windows/x64/runner/Release/"
        $zipFileName = "abbi-${{ github.ref_name }}.zip"
        $outputPath = "dist/$zipFileName"
        
        New-Item -ItemType Directory -Force -Path "dist"
        
        Compress-Archive -Path $sourcePath -DestinationPath $outputPath
      shell: powershell

    - name: Upload Windows Zip Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-app-zip
        path: dist/abbi-${{ github.ref_name }}.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/abbi-${{ github.ref_name }}.zip
